ova_inc/apps/client/urls.py
from . import views
from django.urls import path

app_name = 'client'
urlpatterns = [
    path('', views.main, name="main"),
    path('register/', views.register, name="register"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout")
]

ova_inc/apps/content/urls.py
from . import views
from django.urls import path

app_name = 'content'
urlpatterns = [
    path('test/', views.tests, name="test")
]

ova_inc/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from other_app.views import home

urlpatterns = [
    path('', home, name='home'),
    path('client/', include('client.urls')),
    path('content/', include('content.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ova_inc/apps/client/models.py
from django.db import models

ova_inc/apps/content/models.py
from django.db import models

from django.contrib.auth.models import User

class Tests(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

class Question(models.Model):
    test = models.ForeignKey(Tests, on_delete=models.CASCADE)
    question_text = models.TextField()

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_text = models.TextField()
    istrue = models.BooleanField()

class Check(models.Model):
    test = models.ForeignKey(Tests, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    rating = models.IntegerField()

ova_inc/apps/other_app/models.py
from django.db import models

# Create your models here.

ova_inc/apps/client/forms.py
from django.forms import ModelForm, TextInput
from django.contrib.auth.models import User

class RegForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password', 'email']

        widgets = {
            'username': TextInput(attrs={
                'placeholder': 'Ім\'я користувача'
            }),
            'password': TextInput(attrs={
                'placeholder': 'Пароль',
                'type': 'password'
            }),
            'email': TextInput(attrs={
                'placeholder': 'Email',
                'type': 'email'
            }),
        }

class LoginForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']
        
        widgets = {
            'username': TextInput(attrs={
                'placeholder': 'Ім\'я користувача'
            }),
            'password': TextInput(attrs={
                'placeholder': 'Пароль',
                'type': 'password'
            }),
        }
        

ova_inc/apps/content/forms.py
from django.forms import ModelForm, Form, TextInput, BooleanField, CharField, formset_factory

from django.contrib.auth.models import User
from .models import Tests, Question, Answer

class TestsForm(ModelForm):
    class Meta:
        model = Tests
        fields = ['name']

        widgets = {
            'name': TextInput(attrs={
                'placeholder': 'Назва тесту'
            }),
        }

class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ['question_text']
        
        widgets = {
            'question_text': TextInput(attrs={
                'placeholder': 'Текст питання'
            }),
        }


class AnswerForm(Form):
    answer_text = CharField()
    is_true = BooleanField(required=False)


class Multiform:
    def __init__(self, answer_fields: int, question_fields: int) -> None:
        self.answer_fields = answer_fields
        self.question_fields = question_fields

        self.AnswerFormSet = formset_factory(AnswerForm, extra=self.answer_fields)
        self.QuestionFormSet = formset_factory(QuestionForm, extra=self.question_fields)

ova_inc/apps/client/views.py
from django.shortcuts import render
from django.shortcuts import redirect

from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

from .forms import RegForm, LoginForm

def main(request):
    if request.user.is_authenticated:
        return render(request, 'client/main.html',
                      {'users': User.objects.get(username=request.user)})
    else:
        return render(request, 'client/main.html')

def register(request):
    if request.method == "POST":
        form = RegForm(request.POST)

        try:
            user = User.objects.create_user(form['username'].value(),
                                            form['email'].value(),
                                            form['password'].value())
            user.save()
            auth_login(request, user)

            return redirect('/client/')
        except:
            return render(request, 'client/register.html', {'form': RegForm(),
                                                            'error': True})

    if not request.user.is_authenticated:
        return render(request, 'client/register.html', {'form': RegForm()})
    else:
        return redirect('/client/')

def login(request):
    if request.method == "POST":
        user = User.objects.all()
        form = LoginForm(request.POST)

        user = authenticate(username=form['username'].value(),
                            password=form['password'].value())

        if user is not None:
            auth_login(request, user)
            return redirect('/client/')

    if not request.user.is_authenticated:
        return render(request, 'client/login.html', {'form': LoginForm()})
    else:
        return redirect('/client/')

def logout(request):
    auth_logout(request)
    return redirect('/client/')

ova_inc/apps/content/views.py
from django.shortcuts import render

from .models import *
from .forms import TestsForm, QuestionForm, AnswerForm, Multiform

def tests(request):
    multiform = Multiform(answer_fields=4, question_fields=1)

    if request.method == "POST":
        test_form = TestsForm(request.POST)
        question_form = multiform.QuestionFormSet(request.POST)
        answer_form = multiform.AnswerFormSet(request.POST)
        
        if 'add' in request.POST:
             multiform = Multiform(answer_fields=12, question_fields=3)

        if (answer_form.is_valid() and
            test_form.is_valid() and
            question_form.is_valid()):

            tests = Tests.objects.create(author=request.user,
                                         name=test_form['name'].value())
            question = Question.objects.create(test=tests,
                                               question_text=question_form['question_text'].value())
            for i in answer_form.cleaned_data:
                answer = Answer.objects.create(question=question,
                                               answer_text=i['answer_text'],
                                               istrue=i['is_true'])
            
            # tests.save()
            # question.save()
            # answer.save()

    return render(request, 'content/tests.html', {'test_form': TestsForm,
                                                  'question_form': multiform.QuestionFormSet,
                                                  'answer_form': multiform.AnswerFormSet,
                                                  'x': 0})

ova_inc/apps/other_app/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'index.html')

ova_inc/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

ova_inc/templates/client/login.html
{% extends 'base.html' %}

{% block title %}Вхід{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form.username }}<br>
        {{ form.password }}
        <p><button class="btnsub" type="submit">Надіслати</button>
    </form>
{% endblock %}

ova_inc/templates/client/main.html
{% extends 'base.html' %}

{% block title %}Особистий кабінет{% endblock %}

{% block body %}
    {% if users %}
        <div id="{{users.id}}">
            <h1>Ваше і'мя: {{users.username}}</h1>
            <p>Ваш пароль: {{users.password}}</p>
            <p>Ваша пошта: {{users.email}}</p>
        </div>
        <a href="{% url 'client:logout' %}">Вийти</a>
    {% else %}
        <a href="{% url 'client:register' %}">Реєстрація</a>
        <a href="{% url 'client:login' %}">Увійти</a>
    {% endif %}
{% endblock %}

ova_inc/templates/client/register.html
{% extends 'base.html' %}

{% block title %}Реєстрація{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ form.username }}<br>
        {{ form.password }}<br>
        {{ form.email }}
        <p><button class="btnsub" type="submit">Надіслати</button>
    </form>
    {% if error %}
        <p>Введіть інший логін (такий вже існує)</p>
    {% endif %}
{% endblock %}

ova_inc/templates/content/tests.html
{% extends 'base.html' %}

{% block title %}Створення тестів{% endblock %}

{% block body %}
    <form method="post">
        {% csrf_token %}
        {{ test_form.as_p }}<br>
        {{ question_form.0}}<br>

        {% with steps=0 %}
        {% for i in answer_form %}
            {{ i.as_p }}
            {% if forloop.counter|divisibleby:"4" and not forloop.last %}
                {{forloop.counter // 4}}
                {{ question_form.forloop.counter }}
                {% with steps=steps|add:1 %}
                    {{ steps }}
                {% endwith %}
            {% endif %}
        {% endfor %}
        {% endwith %}

        {% if user.is_authenticated %}
            <p><button type="submit">Надіслати</button>
        {% endif %}
    </form>

    <form method="post">
        {% csrf_token %}
        <p><button type="submit" name="add">Додати поле</button>
    </form>
{% endblock %}

ova_inc/templates/index.html
{% extends 'base.html' %}

{% block title %}Головна{% endblock %}

{% block body %}
    <a href="{% url 'client:main' %}">Особистий кабінет</a>
    <a href="{% url 'content:test' %}">Створити тест</a>
{% endblock %}